# Generated by Django 5.1.7 on 2025-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0002_alter_cart_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('cart', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('orderhistory', models.CharField(max_length=1000)),
            ],
        ),
    ]
