# Generated by Django 5.1.7 on 2025-05-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cart',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='orderhistory',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
