# Generated by Django 5.1.7 on 2025-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0004_alter_users_cart_alter_users_orderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(5, 'Size 5'), (6, 'Size 6'), (7, 'Size 7'), (8, 'Size 8'), (9, 'Size 9'), (10, 'Size 10'), (11, 'Size 11'), (12, 'Size 12')])),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('bata', 'Bata'), ('woodland', 'Woodland')], max_length=20)),
                ('category', models.CharField(choices=[('mens', "Men's Shoes"), ('womens', "Women's Shoes"), ('sports', 'Sports Shoes'), ('formal', 'Formal Shoes'), ('casual', 'Casual Shoes'), ('sneakers', 'Sneakers'), ('slippers', 'Slippers')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='shoes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_sizes', models.ManyToManyField(to='EmployeeManagement.shoesize')),
            ],
        ),
    ]
