# Generated by Django 5.1.7 on 2025-06-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0005_shoesize_shoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='available_sizes',
        ),
    ]
