# Generated by Django 5.1.7 on 2025-06-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0006_remove_shoe_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='wishlist',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
